name:                clash-shake
version:             0.4.0
category:            Hardware, Shake
synopsis:            Shake rules for building Clash programs
description: |
  Shake rules for building Clash programs and synthesizing FPGA
  configuration. Contains build rules for Xilinx ISE, Xilinx Vivado,
  Intel Quartus, F4PGA for Xilinx, and Yosys for ECP-5 and toolchains.  See
  <https://github.com/gergoerdi/clash-pong/> for an example project.
github:              gergoerdi/clash-shake
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2021-2022 Gergő Érdi


dependencies:
  - base >= 4.14 && < 5
  - shake < 0.20

  - clash-prelude >= 1.4.2 && < 2.0
  - clash-lib  >= 1.4.2 && < 2.0
  - clash-ghc >= 1.4.2 && < 2.0

  - directory < 2
  - bytestring < 0.13
  - stache <= 3
  - aeson < 3
  - text < 3
  - unordered-containers <= 1
  - split < 0.3

source-dirs:
  - src

library:
  exposed-modules:
    - Clash.Shake
    - Clash.Shake.Xilinx
    - Clash.Shake.Intel
    - Clash.Shake.F4PGA
    - Clash.Shake.SymbiFlow
    - Clash.Shake.ECP5

extra-source-files:
  - template/xilinx-ise/project.tcl.mustache
  - template/xilinx-vivado/project-build.tcl.mustache
  - template/xilinx-vivado/project.tcl.mustache
  - template/xilinx-vivado/upload.tcl.mustache
  - template/intel-quartus/project.tcl.mustache
