name:                clash-shake
version:             0.2.1
category:            Hardware, Shake
synopsis:            Shake rules for building Clash programs
description: |
  Shake rules for building Clash programs and synthesizing FPGA
  configuration. Contains build rules for Xilinx ISE, Xilinx Vivado,
  Intel Quartus and the open-source SymbiFlow toolchains.  See
  <https://github.com/gergoerdi/clash-pong/> for an example project.
github:              gergoerdi/clash-shake
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2021 Gergő Érdi


dependencies:
  - base >= 4.14 && < 5
  - shake

  - clash-prelude ^>= 1.4.2
  - clash-lib  ^>= 1.4.2
  - clash-ghc ^>= 1.4.2

  - directory
  - bytestring
  - stache
  - aeson
  - text
  - unordered-containers
  - split

source-dirs:
  - src

library:
  exposed-modules:
    - Clash.Shake
    - Clash.Shake.Xilinx
    - Clash.Shake.Intel
    - Clash.Shake.SymbiFlow

extra-source-files:
  - template/xilinx-ise/project.tcl.mustache
  - template/xilinx-vivado/project-build.tcl.mustache
  - template/xilinx-vivado/project.tcl.mustache
  - template/xilinx-vivado/upload.tcl.mustache
  - template/intel-quartus/project.tcl.mustache
